Base ="portfolio"
  command = "npm run build"
  publish = "build"
=======
[build]
  command = "npm run build"
  publish = "build"
>>>>>>> REPLACE

[build.environment]
  NODE_VERSION = "18.18.0"
